spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
#      routes:
#        - id: elco-zhuchi-usercenter
#          uri: lb://elco-zhuchi-usercenter
#          predicates:
#            - Path=/**
#          filters:
#            - StripPrefix=1
#        - id: elco-zhuchi-oauth
#          uri: http://localhost:8031
#          predicates:
#            - Path=/**
#          filters:
#            - StripPrefix=1
whitelist:
  urls:
    - "/elco-zhuchi-oauth/oauth/token"
    - "/elco-zhuchi-oauth/oauth/public_key"
    - "/elco-zhuchi-usercenter/doc.html"
    - "/elco-zhuchi-usercenter/swagger-resources/**"
    - "/elco-zhuchi-usercenter/webjars/**"
    - "/elco-zhuchi-usercenter/swagger-ui.html"
    - "/elco-zhuchi-usercenter/v2/**"
    - "/elco-zhuchi-usercenter/subSystem/getSubSystemList"
    - "/elco-zhuchi-usercenter/subSystem/getSubSystemAndAuthorityByPage"
    - "/elco-zhuchi-usercenter/subSystem/getSubsystemAuthorityBySubsystemId"
    - "/elco-zhuchi-usercenter/dept/getDeptList"
    - "/elco-zhuchi-usercenter/user/getUserDetail"
    - "/elco-zhuchi-usercenter/user/addUserSubsystemAndSubsystemAuthority"